proxy:
  listen_port: ":5003"

servers:
  - name: "Tabby:QwQ-32B"
    url: "http://127.0.0.1:5001"
  - name: "Tabby:Qwen-2.5-Coder-32B"
    url: "http://127.0.0.1:5002"

routing:
  rules:
    - model: "QwQ-32B"
      server: "Tabby:QwQ-32B"
    - model: "Q25_32B-coder-5bpw"
      server: "Tabby:Qwen-2.5-Coder-32B"
  default_server: "Tabby:QwQ-32B"